@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!$domains_root_path = ..

!define actors $domains_root_path/_shared/actors
!define external_systems $domains_root_path/_shared/external_systems

!include external_systems/ok_official_api.iuml
!include external_systems/vk_official_api.iuml
!include actors/operator.iuml
!include actors/amo_operator.iuml

skinparam wrapWidth 500
LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title
    <b>FeedbackPublicationArch v2022.05.26</b>
    <i>Система обратной связи</i>
end title

System(message_processing_system, "Система обработки сообщений", "Web-интерфейс, публикация постов в соц сетях")
System_Ext(amo_crm, "AMO CRM", "Просмотр заявок и отправка ответов")

Rel_D(operator, message_processing_system, "Отвечает на сообщение", "Внутренний REST API")
Rel_D(amo_operator, amo_crm, "Отвечает на заявки")
Rel_R(message_processing_system, amo_crm, "Отвечает на сообщение", "Внутренний REST API")
Rel_D(message_processing_system, vk_official_api, "Публикация", "HTTP")
Rel_D(message_processing_system, ok_mobile, "Публикация", "HTTP")

@enduml
